name: Request Construct Deletion
description: Propose removing a construct from the dataset
labels: ["delete-construct"]
assignees: []
body:
  - type: input
    id: construct_title
    attributes:
      label: Construct title or ID
      description: Name exactly as listed
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for removal
      description: Explain why this construct should be deleted
    validations:
      required: true
