name: Reference submission
description: Add a peer-reviewed source to the literature database
labels: ["reference"]
assignees: []
body:
  - type: dropdown
    id: entry_type
    attributes:
      label: BibTeX entry type
      description: Select the closest reference category
      options:
        - article
        - book
        - inproceedings
        - techreport
        - misc
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: Full title of the paper, chapter, or book
    validations:
      required: true
  - type: input
    id: authors
    attributes:
      label: Author(s)
      description: e.g., Smith J., Doe A.
    validations:
      required: true
  - type: input
    id: year
    attributes:
      label: Year
    validations:
      required: true
  - type: input
    id: journal
    attributes:
      label: Journal / Booktitle
      description: Required for articles or conference papers
  - type: input
    id: publisher
    attributes:
      label: Publisher
      description: Organization or publisher name (if applicable)
  - type: input
    id: address
    attributes:
      label: Address
      description: City or location (if applicable)
  - type: input
    id: url
    attributes:
      label: DOI or URL
    validations:
      required: true
  - type: input
    id: related_constructs
    attributes:
      label: Related construct(s)
      description: Select existing constructs or enter new ones separated by commas
  - type: input
    id: axis
    attributes:
      label: SERA skill axis
      description: sense, explain, respond, adapt, or extended
  - type: textarea
    id: relevance
    attributes:
      label: Short note on relevance
