name: backup-db
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install node-fetch
      - name: Run backup
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          timestamp=$(date +'%Y%m%d_%H%M%S')
          outdir="backups/$timestamp"
          node scripts/dump_supabase.js "$outdir"
      - name: Commit backup
        uses: EndBug/add-and-commit@v9
        with:
          add: 'backups/*'
          message: 'Automated database backup'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
