name: export-constructs
on:
  issues:
    types: [opened, edited, deleted]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Export construct issues to JSON
        id: export
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'construct',
              state: 'open',
              per_page: 100,
            });
              const map = {};
              for (const issue of issues) {
                const key = issue.title.toLowerCase();
                const existing = map[key];
                if (!existing || new Date(issue.updated_at) > new Date(existing.updated_at)) {
                  map[key] = issue;
                }
              }
              const deduped = Object.values(map);
              const data = deduped.map(i => ({
                number: i.number,
                title: i.title,
                user: i.user.login,
                url: i.html_url,
                created_at: i.created_at,
                body: i.body
              }));
            fs.mkdirSync('data', { recursive: true });
            fs.mkdirSync('docs', { recursive: true });
            const json = JSON.stringify(data, null, 2);
            fs.writeFileSync('data/construct_submissions.json', json);
            fs.writeFileSync('docs/construct_submissions.json', json);
      - name: Commit updates
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data/construct_submissions.json docs/construct_submissions.json'
          message: 'Update construct submissions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
